(function() {var implementors = {};
implementors["psutil"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"psutil/process/enum.State.html\" title=\"enum psutil::process::State\">State</a>",synthetic:false,types:["psutil::process::State"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"psutil/process/struct.Memory.html\" title=\"struct psutil::process::Memory\">Memory</a>",synthetic:false,types:["psutil::process::Memory"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"psutil/process/struct.Process.html\" title=\"struct psutil::process::Process\">Process</a>",synthetic:false,types:["psutil::process::Process"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"psutil/system/struct.VirtualMemory.html\" title=\"struct psutil::system::VirtualMemory\">VirtualMemory</a>",synthetic:false,types:["psutil::system::VirtualMemory"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"psutil/system/struct.SwapMemory.html\" title=\"struct psutil::system::SwapMemory\">SwapMemory</a>",synthetic:false,types:["psutil::system::SwapMemory"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"psutil/system/struct.LoadAverage.html\" title=\"struct psutil::system::LoadAverage\">LoadAverage</a>",synthetic:false,types:["psutil::system::LoadAverage"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
